spring:
    application:
        name: rocknrollalbumart

mygreeting: "A message from docker-rocknrollConfig server on github refreshing one more time"

db:
   connection:"connection string..."
   host:127.0.0.1
   port:8080
