spring:
    application:
        name: rocknrollConfig

mygreeting: "A configuration message from rocknrollConfig server on github but for rocknrollConfig microservice"

db:
   connection:"connection string..."
   host:127.0.0.1
   port:8080
