spring:
    application:
        name: rocknrollalbumart
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mygreeting: "A message from rocknrollConfig server on github but for rocknrollalbum art microservice"

db:
   connection:"connection string..."
   host:127.0.0.1
   port:8080
